sudo: required
dist: trusty

#workaround for https://github.com/travis-ci/travis-ci/issues/5227
addons:
  hostname: cobrax-tester

os: linux
language: generic
cache:
  directories:
  - depends/built
  - depends/sdk-sources
  - $HOME/.ccache
env:
  global:
    - MAKEJOBS=-j3
    - RUN_TESTS=false
    - CHECK_DOC=0
    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
    - CCACHE_SIZE=100M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
    - PYTHON_DEBUG=1
    - WINEDEBUG=fixme-all
  matrix:
# ARM
    - REASON=ARM HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" CHECK_DOC=1 GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
# Win32
    - REASON=Win32 HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="python3 nsis g++-mingw-w64-i686 wine1.6 bc" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
# 32-bit + dash
    - REASON=Linux32 HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc python3-zmq" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash" PYZMQ=true
# Win64
    - REASON=Win64 HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine1.6 bc" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
# cobraxd
    - REASON=Linux64 HOST=x86_64-unknown-linux-gnu PACKAGES="bc python3-zmq" DEP_OPTS="NO_UPNP=1 DEBUG=1" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports CPPFLAGS=-DDEBUG_LOCKORDER" PYZMQ=true
# No wallet
#    - REASON=NodeOnly HOST=x86_64-unknown-linux-gnu PACKAGES="python3" DEP_OPTS="NO_WALLET=1" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
# Cross-Mac
    - REASON=MacOSX HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev" BITCOIN_CONFIG="--enable-reduce-exports" OSX_SDK=10.11 GOAL="deploy"

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
install:
  - if [ "$PYZMQ" = "true" ]; then pip install pyzmq --user ; fi
  - if [ -n "$PPA" ]; then travis_retry sudo add-apt-repository "$PPA" -y; fi
  - if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
  - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
  - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
before_script:
  - unset CC; unset CXX
  - if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/check-doc.py; fi
  - mkdir -p depends/SDKs depends/sdk-sources
  - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
  - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
  - make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
script:
  - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
  - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
  - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
  - BITCOIN_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
  - depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
  - test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
  - ./configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
  - make distdir PACKAGE=bitcoin VERSION=$HOST
  - cd bitcoin-$HOST
  - ./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
  - make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
  - if [ "$RUN_TESTS" = "true" ]; then make $MAKEJOBS check VERBOSE=1; fi
  #- if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.py --coverage; fi
after_script:
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_COMMIT_LOG
after_success:
  - find $OUTDIR
  - export VERSION=$REASON-$TRAVIS_BRANCH
  - if [ "$REASON" = "ARM" ]; then cd $OUTDIR && cp -a bin cobrax-Core-$VERSION && rm cobrax-Core-$VERSION/*test* && zip -r cobrax-Core-$VERSION.zip cobrax-Core-$VERSION; fi
  - if [ "$REASON" = "Win32" ]; then cd $OUTDIR && cp -a bin cobrax-Core-$VERSION && rm cobrax-Core-$VERSION/*test* && zip -r cobrax-Core-$VERSION.zip cobrax-Core-$VERSION; fi
  - if [ "$REASON" = "Win64" ]; then cd $OUTDIR && cp -a bin cobrax-Core-$VERSION && rm cobrax-Core-$VERSION/*test* && zip -r cobrax-Core-$VERSION.zip cobrax-Core-$VERSION; fi
  - if [ "$REASON" = "Linux32" ]; then cd $OUTDIR && cp -a bin cobrax-Core-$VERSION && rm cobrax-Core-$VERSION/*test* && zip -r cobrax-Core-$VERSION.zip cobrax-Core-$VERSION; fi
  - if [ "$REASON" = "Linux64" ]; then cd $OUTDIR && cp -a bin cobrax-Core-$VERSION && rm cobrax-Core-$VERSION/*test* && zip -r cobrax-Core-$VERSION.zip cobrax-Core-$VERSION; fi
  - if [ "$REASON" = "MacOSX" ]; then mkdir -p $OUTDIR && cd $OUTDIR && cp /home/travis/build/cobraxcoin/cobrax-core/bitcoin-x86_64-apple-darwin11/cobrax-Core.dmg cobrax-Core-$VERSION.dmg; fi
deploy:
  provider: releases
  api_key:
    secure: "JnBaVArM8J3CAavRBeBHFZteP/4cc3YVrXzoqdKX1aS/PZKf8kpoq2LzyvFFfX0uAZ9rjNNjD9cM8CJiLJ8G0QgtYEs8+J/VXQ67PtPTvZf8QiIU0pVgWeGm86gpYMH/pXQXq3+8DSPE0+QGGBe+B+pNer9Wmxw0hzQY1+XL78w81euaEbTHtvlifSqR8C9aEE8zO425SxfmXl5U6YeVlj1NvCeZNIbfnzjOCSz5T0nkRVT278t7A/BJBsfB6STLjnzFoWpZWk7gWGgzzEHKy+8+zlexC4sRJpwxZO5f8gp0rCC3u92VDQDZkzRYt6uzrHysXTYcjfWfIOf6nXw22cxTqMdTZs2wzJNVwkKKOOkuBx5ULP4Iokpy3p/TXQRwUUpH7APfDmm4TX01hSlJK7sgkL+peXnavD66+VfFwkrcTpq9ZoPbrpp24MbaKNUEa+FdpUWeJPNggHzKdx3tZ6JUunS6rpFhED/WcYoCpiknBkqXNN3AB2+UxfuE6G+pL3l/oa9n9kuhnCD4KexIWP2rfCD7AqCjus1ZSz1iD97LyIu2UKj0qZFdjePqmwigrXIgzpgx8H39Y7lolxO1K5VUXmWCvNGkAzXE8RMQfS01UB1ZiAZz7b6Aac3yKkMQ6vnwajMP3HiAVkoab9WNdB590je+07gYqqyrR5kiqHQ="
  file_glob: true
  file:
    - $OUTDIR/*.dmg
    - $OUTDIR/*.zip
  skip_cleanup: true
  on:
    tags: true